### ISSUE TITLE
Confusing Syntax

### ISSUE THREAD

**Issue by srutisriram** [learn-co-curriculum/ruby-public-private-methods-readme#11]
Here, the header says "Why use an ATTR ACCESSOR", but the paragraph below really seems like it's answering instead why setter/getter methods are _more_ useful than attr_accessor, which makes it seem like I'm missing the point (which I don't think I am)

**Comment by AnnJohn** [comment]
thanks @srutisriram we'll look into this. 

@ruchiramani can you go through the reading to see if there are any style/tone issues to address pertaining to the above issue? thanks

**Comment by ruchiramani** [comment]
@srutisriram attr_accessor would be equivalent with getter-setter "instance" methods both.
