### ISSUE TITLE
Wrong variable in #intro?

### ISSUE THREAD

**Issue by WilliamJones62** [learn-co-curriculum/ruby-public-private-methods-readme#19]
In the #intro method should it be using the @name variable and not the name variable. I thought the name variable only has local scope and so would be unavailable in the intro method. Please see below,

class Bartender
  attr_accessor :name

  def initialize(name)
    @name = name
  end

  def intro
    "Hello, my name is #{name}!"
  end
end

phil = Bartender.new("Phil")
phil.intro
# => "Hello, my name is Phil!"

**Comment by JeffKatzy** [comment]
No because `name` does not refer to a local variable, but rather the method def name, which attr_accessor produces.
