### ISSUE TITLE
Cat photo

### ISSUE THREAD

**Issue by bacitracin** [learn-co-curriculum/ruby-public-private-methods-readme#9]
I feel silly raising this as an "issue," but the cat image at the bottom of the lesson isn't Lil Bub it's Grumpy Cat. Here's a good Lil Bub bday photo from her official 2nd birthday video: https://i.ytimg.com/vi/HAtMh03rkT0/maxresdefault.jpg

**Comment by AnnJohn** [comment]
ha @bacitracin not silly at all. we'll update this but this isn't very high on our priority list so it might take some time.
